ALTER TABLE provider_keys ADD COLUMN IF NOT EXISTS model_overrides JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE provider_keys ADD COLUMN IF NOT EXISTS test_model TEXT NOT NULL DEFAULT '';

ALTER TABLE oauth_accounts ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '';
ALTER TABLE oauth_accounts ADD COLUMN IF NOT EXISTS email TEXT NOT NULL DEFAULT '';
ALTER TABLE oauth_accounts ADD COLUMN IF NOT EXISTS provider_account_id TEXT NOT NULL DEFAULT '';
ALTER TABLE oauth_accounts ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';
ALTER TABLE oauth_accounts ADD COLUMN IF NOT EXISTS quota_used DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE oauth_accounts ADD COLUMN IF NOT EXISTS quota_total DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE oauth_accounts ADD COLUMN IF NOT EXISTS quota_unit TEXT NOT NULL DEFAULT '';
ALTER TABLE oauth_accounts ADD COLUMN IF NOT EXISTS last_quota_check TIMESTAMPTZ NULL;
ALTER TABLE oauth_accounts ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';
ALTER TABLE oauth_accounts ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS gateway_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
